/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.RequestError

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Base class to all responses
 * @param result 
 * @param errors 
 */
@Serializable
data class BaseResponse (
    @SerialName(value = "result") val result: BaseResponse.Result? = null,
    @SerialName(value = "errors") val errors: kotlin.collections.List<RequestError>? = null
) {

    /**
     * 
     * Values: SUCCESS,ERROR
     */
    @Serializable
    enum class Result(val value: kotlin.String) {
        @SerialName(value = "success") SUCCESS("success"),
        @SerialName(value = "error") ERROR("error");
    }
}

