/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The structure with a description of a requested page in requests of lists
 * @param size The size of a requested page
 * @param lastId ID of the last object of the previous page
 */
@Serializable
data class BasePaginatedRequest (
    /* The size of a requested page */
    @SerialName(value = "size") val size: kotlin.Int? = null,
    /* ID of the last object of the previous page */
    @SerialName(value = "lastId") val lastId: kotlin.String? = null
)

