/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The structure with data about the workout to request about creation
 * @param date Date of workout
 * @param duration Duration of workout
 * @param recoveryTime Recovery time between exercises
 * @param exercises 
 */
@Serializable
data class CreatableWorkout (
    /* Date of workout */
    @SerialName(value = "date") val date: kotlin.String? = null,
    /* Duration of workout */
    @SerialName(value = "duration") val duration: kotlin.Double? = null,
    /* Recovery time between exercises */
    @SerialName(value = "recoveryTime") val recoveryTime: kotlin.Double? = null,
    @SerialName(value = "exercises") val exercises: kotlin.collections.Map<kotlin.String, kotlin.String>? = null
)

