/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.CreatableExercise
import ru.otus.otuskotlin.workout.mp.transport.models.OneSet

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param exercise 
 * @param sets 
 * @param modificationBlockExercises 
 */
@Serializable
data class Exercises (
    @SerialName(value = "exercise") val exercise: CreatableExercise? = null,
    @SerialName(value = "sets") val sets: kotlin.collections.List<OneSet>? = null,
    @SerialName(value = "modificationBlockExercises") val modificationBlockExercises: Exercises.ModificationBlockExercises? = null
) {

    /**
     * 
     * Values: NONE,WITHOUT_LAST_RIGHT,WITHOUT_LAST_LEFT
     */
    @Serializable
    enum class ModificationBlockExercises(val value: kotlin.String) {
        @SerialName(value = "NONE") NONE("NONE"),
        @SerialName(value = "WITHOUT_LAST_RIGHT") WITHOUT_LAST_RIGHT("WITHOUT_LAST_RIGHT"),
        @SerialName(value = "WITHOUT_LAST_LEFT") WITHOUT_LAST_LEFT("WITHOUT_LAST_LEFT");
    }
}

