/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Description of request processing error
 * @param message 
 * @param field 
 */
@Serializable
data class RequestError (
    @SerialName(value = "message") val message: kotlin.String? = null,
    @SerialName(value = "field") val field: kotlin.String? = null
)

