/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.ExercisePermissions
import ru.otus.otuskotlin.workout.mp.transport.models.ResponseExerciseAllOf
import ru.otus.otuskotlin.workout.mp.transport.models.UpdatableExercise

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The structure describing the declaration in the response
 * @param title Название упражнения
 * @param description 
 * @param targetMuscleGroup 
 * @param synergisticMuscleGroup 
 * @param executionTechnique 
 * @param id 
 * @param permissions 
 */
@Serializable
data class ResponseExercise (
    /* Название упражнения */
    @SerialName(value = "title") val title: kotlin.String? = null,
    @SerialName(value = "description") val description: kotlin.String? = null,
    @SerialName(value = "targetMuscleGroup") val targetMuscleGroup: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "synergisticMuscleGroup") val synergisticMuscleGroup: kotlin.collections.List<kotlin.String>? = null,
    @SerialName(value = "executionTechnique") val executionTechnique: kotlin.String? = null,
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "permissions") val permissions: kotlin.collections.Set<ExercisePermissions>? = null
)

