/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.Exercises
import ru.otus.otuskotlin.workout.mp.transport.models.Permissions
import ru.otus.otuskotlin.workout.mp.transport.models.ResponseExerciseAllOf
import ru.otus.otuskotlin.workout.mp.transport.models.UpdatableWorkout

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The structure describing the workout in the response
 * @param date Date of workout
 * @param duration Duration of workout
 * @param recoveryTime Recovery time between exercises
 * @param modificationWorkout 
 * @param exercises 
 * @param id 
 * @param permissions 
 */
@Serializable
data class ResponseWorkout (
    /* Date of workout */
    @SerialName(value = "date") val date: kotlin.String? = null,
    /* Duration of workout */
    @SerialName(value = "duration") val duration: kotlin.Double? = null,
    /* Recovery time between exercises */
    @SerialName(value = "recoveryTime") val recoveryTime: kotlin.Double? = null,
    @SerialName(value = "modificationWorkout") val modificationWorkout: ResponseWorkout.ModificationWorkout? = null,
    @SerialName(value = "exercises") val exercises: kotlin.collections.List<Exercises>? = null,
    @SerialName(value = "id") val id: kotlin.String? = null,
    @SerialName(value = "permissions") val permissions: kotlin.collections.Set<Permissions>? = null
) {

    /**
     * 
     * Values: CLASSIC,CIRCUIT
     */
    @Serializable
    enum class ModificationWorkout(val value: kotlin.String) {
        @SerialName(value = "CLASSIC") CLASSIC("CLASSIC"),
        @SerialName(value = "CIRCUIT") CIRCUIT("CIRCUIT");
    }
}

