/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 * @param date Date of workout
 * @param searchMuscleGroup Text of search of a muscle group
 * @param searchExercise Text of search of an exercise in workouts
 */
@Serializable
data class SearchWorkoutRequestAllOf (
    /* Date of workout */
    @SerialName(value = "date") val date: kotlin.String? = null,
    /* Text of search of a muscle group */
    @SerialName(value = "searchMuscleGroup") val searchMuscleGroup: kotlin.String? = null,
    /* Text of search of an exercise in workouts */
    @SerialName(value = "searchExercise") val searchExercise: kotlin.String? = null
)

