/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.BaseMessage
import ru.otus.otuskotlin.workout.mp.transport.models.BaseResponse
import ru.otus.otuskotlin.workout.mp.transport.models.RequestError
import ru.otus.otuskotlin.workout.mp.transport.models.SearchWorkoutRequestAllOf

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Structure to request a search of an exercise
 * @param messageType A discriminator contaiting the message class type and used to deserialization
 * @param result 
 * @param errors 
 * @param date Date of workout
 * @param searchMuscleGroup Text of search of a muscle group
 * @param searchExercise Text of search of an exercise in workouts
 */
@Serializable
data class SearchWorkoutRequest (
    /* A discriminator contaiting the message class type and used to deserialization */
    @SerialName(value = "messageType") override val messageType: kotlin.String? = null,
    @SerialName(value = "result") val result: SearchWorkoutRequest.Result? = null,
    @SerialName(value = "errors") val errors: kotlin.collections.List<RequestError>? = null,
    /* Date of workout */
    @SerialName(value = "date") val date: kotlin.String? = null,
    /* Text of search of a muscle group */
    @SerialName(value = "searchMuscleGroup") val searchMuscleGroup: kotlin.String? = null,
    /* Text of search of an exercise in workouts */
    @SerialName(value = "searchExercise") val searchExercise: kotlin.String? = null
) : BaseMessage {

    /**
     * 
     * Values: SUCCESS,ERROR
     */
    @Serializable
    enum class Result(val value: kotlin.String) {
        @SerialName(value = "success") SUCCESS("success"),
        @SerialName(value = "error") ERROR("error");
    }
}

