/**
* Workout
* Workout is an app for building a workout program
*
* The version of the OpenAPI document: 0.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package ru.otus.otuskotlin.workout.mp.transport.models

import ru.otus.otuskotlin.workout.mp.transport.models.CreatableWorkout
import ru.otus.otuskotlin.workout.mp.transport.models.ExercisesBlock
import ru.otus.otuskotlin.workout.mp.transport.models.UpdatableExerciseAllOf

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Structure for a data about the workout in request to update
 * @param date Date of workout
 * @param duration Duration of workout
 * @param recoveryTime Recovery time between exercises
 * @param modificationWorkout 
 * @param exercisesBlock 
 * @param id 
 */
@Serializable
data class UpdatableWorkout (
    /* Date of workout */
    @SerialName(value = "date") val date: kotlin.String? = null,
    /* Duration of workout */
    @SerialName(value = "duration") val duration: kotlin.Double? = null,
    /* Recovery time between exercises */
    @SerialName(value = "recoveryTime") val recoveryTime: kotlin.Double? = null,
    @SerialName(value = "modificationWorkout") val modificationWorkout: UpdatableWorkout.ModificationWorkout? = null,
    @SerialName(value = "exercisesBlock") val exercisesBlock: kotlin.collections.List<ExercisesBlock>? = null,
    @SerialName(value = "id") val id: kotlin.String? = null
) {

    /**
     * 
     * Values: CLASSIC,CIRCUIT
     */
    @Serializable
    enum class ModificationWorkout(val value: kotlin.String) {
        @SerialName(value = "CLASSIC") CLASSIC("CLASSIC"),
        @SerialName(value = "CIRCUIT") CIRCUIT("CIRCUIT");
    }
}

