openapi: 3.0.3
info:
  title: Exercise
  description: 'Description of the transport model of the exercise.'
  license:
    name: MIT
  version: 0.0.1
paths:
  /init:
    post:
      tags:
        - exercise
      summary: Get status on initialization
      operationId: initExercise
      requestBody:
        description: The request object to an initialization on start application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitExerciseResponse'
  /create:
    post:
      tags:
        - exercise
      summary: Create a new exercise
      operationId: createExercise
      requestBody:
        description: The request object to create a new exercise
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateExerciseResponse'
  /read:
    post:
      tags:
        - exercise
      summary: Get information about an exercise
      operationId: readExercise
      requestBody:
        description: The request object to obtain an exercise information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadExerciseResponse'
  /update:
    post:
      tags:
        - exercise
      summary: Update information about an exercise
      operationId: updateExercise
      requestBody:
        description: The request object to update an exercise information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateExerciseResponse'
  /delete:
    post:
      tags:
        - exercise
      summary: Delete an exercise
      operationId: deleteExercise
      requestBody:
        description: The request object to delete an exercise
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteExerciseResponse'
  /search:
    post:
      tags:
        - exercise
      summary: Search the exercises
      operationId: searchExercise
      requestBody:
        description: The request object to search the exercises
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchExerciseRequest'
        required: true
      responses:
        200:
          description: All responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchExerciseResponse'

components:
  schemas:

    CreatableExercise:
      type: object
      description: The structure with data about the exercise to request about creation
      properties:
        title:
          type: string
          description: Exercise name
        description:
          type: string
          description: Exercise description
        targetMuscleGroup:
          type: array
          items:
            type: string
        synergisticMuscleGroup:
          type: array
          items:
            type: string
        executionTechnique:
          type: string

    UpdatableExercise:
      description: Structure for a data about the exercise in request to update
      allOf:
        - $ref: '#/components/schemas/CreatableExercise'
        - type: object
          properties:
            id:
              type: string

    InitExerciseRequest:
      description: Structure to request the initial state when starting the web client
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object

    InitExerciseResponse:
      description: Structure to respond with the initial state when starting the web client
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object

    CreateExerciseRequest:
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            createExercise:
              $ref: '#/components/schemas/CreatableExercise'
            debug:
              allOf:
                - $ref: './spec-workout-api.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - nameEmpty
                        - errorDb

    CreateExerciseResponse:
      description: The structure to respond to a request about the declaration an exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            createdExercise:
              $ref: '#/components/schemas/ResponseExercise'

    ResponseExercise:
      description: The structure describing the exercise in the response
      allOf:
        - $ref: '#/components/schemas/UpdatableExercise'
        - type: object
          properties:
            permissions:
              type: array
              uniqueItems: true
              items:
                $ref: './spec-workout-api.yaml#/components/schemas/Permissions'

    ReadExerciseRequest:
      description: The structure to get exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            readExerciseId:
              type: string
            debug:
              allOf:
                - $ref: './spec-workout-api.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - errorDb
    ReadExerciseResponse:
      description: The structure to respond to a request with an exercise information
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            readExercise:
              $ref: '#/components/schemas/ResponseExercise'

    UpdateExerciseRequest:
      description: Structure for request an update to an existing exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            updateExercise:
              $ref: '#/components/schemas/UpdatableExercise'
            debug:
              allOf:
                - $ref: './spec-workout-api.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyTitle
                        - errorDb

    UpdateExerciseResponse:
      description: The structure to respond to a request with an exercise information
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            updateExercise:
              $ref: '#/components/schemas/ResponseExercise'

    DeleteExerciseRequest:
      description: The structure to request to delete an exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            deleteExerciseId:
              type: string
            debug:
              allOf:
                - $ref: './spec-workout-api.yaml#/components/schemas/BaseDebugRequest'
                - type: object
                  properties:
                    stub:
                      type: string
                      enum:
                        - success
                        - emptyId
                        - errorDb

    DeleteExerciseResponse:
      description: Structure to respond to a request to delete an exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            deleteExercise:
              $ref: '#/components/schemas/ResponseExercise'

    SearchExerciseRequest:
      description: Structure to request a search of an exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseRequest'
        - type: object
          properties:
            search:
              type: string

    SearchExerciseResponse:
      description: Structure to respond to a request search of exercise
      allOf:
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseMessage'
        - $ref: './spec-workout-api.yaml#/components/schemas/BaseResponse'
        - type: object
          properties:
            foundExercises:
              type: array
              items:
                $ref: '#/components/schemas/ResponseExercise'