POST http://127.0.0.1:8080/exercise/create
Content-Type: application/json

{
  "messageType": "CreateExerciseRequest",
  "requestId": "rID:0001",
  "createExercise": {
    "title": "Приседания со штангой",
    "description": "Базовое упражнение",
    "targetMuscleGroup": [
      "Квадрицепсы"
    ],
    "synergisticMuscleGroup": [
      "Большие ягодичные",
      "Приводящие бедра",
      "Камбаловидные"
    ],
    "executionTechnique": "Выполняющий упражнение приседает и затем встаёт, возвращаясь в положение стоя"
  },
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

###

POST http://127.0.0.1:8080/exercise/read
Content-Type: application/json

{
  "messageType": "ReadExerciseRequest",
  "requestId": "rID:0001",
  "readExerciseId": "eID:0001",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

###

POST http://127.0.0.1:8080/exercise/read
Content-Type: application/json

{
  "messageType": "ReadExerciseRequest",
  "requestId": "12345",
  "readExerciseId": "eID:0002",
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}

###

POST http://127.0.0.1:8080/exercise/update
Content-Type: application/json

{
  "messageType": "UpdateExerciseRequest",
  "requestId": "rID:0003",
  "updateExercise": {
    "title": "Подтягивания",
    "description": "Базовое упражнение",
    "targetMuscleGroup": [
      "Широчайшие мышцы спины"
    ],
    "synergisticMuscleGroup": [
      "Бицепс",
      "Мышцы предплечья"
    ],
    "executionTechnique": "Вися на неподвижной перекладине над головой, нужно постараться подтянуть своё тело вверх до касания грудью (или подбородком) перекладины.",
    "id": "rID:0008"
  },
  "debug": {
    "mode": "stub",
    "stub": "success"
  }
}