POST http://127.0.0.1:8080/workout/create
Content-Type: application/json

{
  "messageType": "CreateWorkoutRequest",
  "requestId": "id:123",
  "createWorkout": {
    "date": "2021-08-11T14:00:00.0Z",
    "duration": 0.0,
    "recoveryTime": 60.0,
    "modificationWorkout": "CLASSIC",
    "exercisesBlock": [
      {
        "exercise": {
          "title": "Глубокие приседания со штангой",
          "description": "Базовое упражнение",
          "targetMuscleGroup": [
            "Квадрицепсы"
          ],
          "synergisticMuscleGroup": [
            "Большие ягодичные",
            "Приводящие бедра",
            "Камбаловидные"
          ],
          "executionTechnique": "При выполнении приседаний можно варьировать положение ног, но обычно рекомендуют ставить носки врозь, а ноги примерно на ширине плеч",
          "id": "eID:00001",
          "permissions": [
            "read"
          ]
        },
        "sets": [
          {
            "performance": [
              {
                "weight": 80.0,
                "measure": "KG",
                "repetition": 10
              }
            ],
            "status": "PLAN",
            "modificationExercise": "NONE"
          }
        ],
        "modificationBlockExercises": "NONE"
      }
    ]
  },
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}

###

POST http://127.0.0.1:8080/workout/read
Content-Type: application/json

{
  "messageType": "ReadWorkoutRequest",
  "requestId": "id:1234",
  "readWorkoutId": "wID:0001",
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}

###

POST http://127.0.0.1:8080/workout/update
Content-Type: application/json

{
  "messageType": "UpdateWorkoutRequest",
  "requestId": "id:123",
  "updateWorkout": {
    "date": "2021-08-11T14:00:00.0Z",
    "duration": 0.0,
    "recoveryTime": 60.0,
    "modificationWorkout": "CLASSIC",
    "exercisesBlock": [
      {
        "exercise": {
          "title": "Приседания со штангой",
          "description": "Базовое упражнение",
          "targetMuscleGroup": [
            "Квадрицепсы"
          ],
          "synergisticMuscleGroup": [
            "Большие ягодичные",
            "Приводящие бедра",
            "Камбаловидные"
          ],
          "executionTechnique": "При выполнении приседаний можно варьировать положение ног, но обычно рекомендуют ставить носки врозь, а ноги примерно на ширине плеч",
          "id": "eID:00001",
          "permissions": [
            "READ"
          ]
        },
        "sets": [
          {
            "performance": [
              {
                "weight": 80.0,
                "measure": "KG",
                "repetition": 10
              }
            ],
            "status": "PLAN",
            "modificationExercise": "NONE"
          }
        ],
        "modificationBlockExercises": "NONE"
      }
    ],
    "id": "wID:00001"
  },
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}

###

POST http://127.0.0.1:8080/workout/delete
Content-Type: application/json

{
  "messageType": "DeleteWorkoutRequest",
  "requestId": "id:1234",
  "deleteWorkoutId": "wID:0001",
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}

###

POST http://127.0.0.1:8080/workout/search
Content-Type: application/json

{
  "messageType": "SearchWorkoutRequest",
  "requestId": "id:1234",
  "search": "Приседания",
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}

###

POST http://127.0.0.1:8080/workout/chainOfExercises
Content-Type: application/json

{
  "messageType": "ReadWorkoutRequest",
  "requestId": "id:1234",
  "readWorkoutId": "wID:0001",
  "debug": {
    "mode": "stub",
    "stubCase": "success"
  }
}